version: 0.2.8-{build}
image: Ubuntu1804
stack: node 12
build_script:
- sh: >-
    node --version

    npm i

    npm i vsce -g

    node ./prepare-version.js

    bash build.sh
artifacts:
- path: '*.vsix'